# railway.toml - конфигурация для Railway
[build]
builder = "dockerfile"
dockerfilePath = "Dockerfile"

[deploy]
startCommand = "/app/start_server.sh"
healthcheckPath = "/"
healthcheckTimeout = 300
restartPolicyType = "always"

# Переменные окружения для Railway
[env]
PORT = { default = "1337" }
BYOND_STARTUP_TIMEOUT = { default = "120" }
