# railway.toml - конфигурация для Railway
[build]
builder = "dockerfile"
dockerfilePath = "Dockerfile"

[deploy]
startCommand = "/app/start_server.sh"
healthcheckPath = "/"
healthcheckTimeout = 300
restartPolicyType = "always"

# Переменные окружения для Railway
[env]
PORT = { default = "1337" }
BYOND_STARTUP_TIMEOUT = { default = "120" }

---

# .dockerignore - оптимизация сборки
.git
.gitignore
README.md
*.md
.env*
.DS_Store
Thumbs.db

# Исключаем ненужные файлы для сборки
node_modules/.cache
.npm
.cache
*.log
*.tmp

# Документация и примеры
docs/
examples/
.github/

---

# railway.json - альтернативная конфигурация
{
  "$schema": "https://railway.app/railway.schema.json",
  "build": {
    "builder": "dockerfile"
  },
  "deploy": {
    "startCommand": "/app/start_server.sh",
    "healthcheckPath": "/",
    "healthcheckTimeout": 300,
    "restartPolicyType": "always"
  }
}
