# railway.json - альтернативная конфигурация
{
  "$schema": "https://railway.app/railway.schema.json",
  "build": {
    "builder": "dockerfile"
  },
  "deploy": {
    "startCommand": "/app/start_server.sh",
    "healthcheckPath": "/",
    "healthcheckTimeout": 300,
    "restartPolicyType": "always"
  }
}
